Feature/nanoflow
FlockOfBirds/progress-circle pull request #10
Opened 2018-04-16 14:50 UTC by jseremba

2018-04-17 12:11 UTC, McDoyen requested changes

2018-04-17 12:11 UTC, McDoyen commented on tslint.json
> +
Missing end of line

2018-04-17 12:11 UTC, McDoyen commented on tsconfig.json
> +
Missing eol

2018-05-09 09:40 UTC, jseremba commented on tslint.json
> +
Done

2018-05-09 09:40 UTC, jseremba commented on tsconfig.json
> +
Done

2018-05-10 13:39 UTC, djkwagala requested changes

2018-05-10 13:39 UTC, djkwagala commented on src/components/ProgressCircleContainer.ts
> +    openPageAs: PageLocation;
use `OpenPageAs` typing

2018-05-10 13:39 UTC, djkwagala commented on src/components/ProgressCircleContainer.ts
> +type PageLocation = "popup" | "modal" | "content";
rename to `OpenPage` or `DisplayPage`

2018-05-11 14:58 UTC, merged